.PHONY : all install

all :

install : 
	@cp -v slib/linux64/thostmduserapi.so /usr/lib64/libthostmduserapi.so
	@cp -v slib/linux64/thosttraderapi.so /usr/lib64/libthosttraderapi.so
	@cp -v slib/linux32/thostmduserapi.so /usr/lib/libthostmduserapi.so
	@cp -v slib/linux32/thosttraderapi.so /usr/lib/libthosttraderapi.so
